#!/bin/sh

# script/studio: Enter a Chef Habitat studio for the application.

set -e
cd "$(dirname "$0")/.."


script/-studio-bootstrap


echo
echo "==> studio: configuring Chef Habitat studio Docker options…"
STUDIO_NAME="${STUDIO_NAME:-b21skel-studio}"
export HAB_DOCKER_OPTS="
    --name ${STUDIO_NAME}
    -p 2190:80
    -p 2196:3306
    -v $(cd ~/.ssh; pwd)/known_hosts:/root/.ssh/known_hosts:ro
    --env STUDIO_DEVELOPER_UID=$(id -u)
    --env STUDIO_DEVELOPER_GID=$(id -g)
"
echo "${HAB_DOCKER_OPTS}"


echo
echo "==> studio: launching Docker-powered Chef Habitat studio…"
hab studio enter -D
